### ISSUE TITLE
An error with secret path

### ISSUE THREAD

**Issue by fboudali** [spring-guides/gs-accessing-vault#4]
Hello,
I got a NPE right after launching the jar. 
Based on this thread : 
https://stackoverflow.com/questions/52100532/how-to-read-vault-kv-with-java-spring-boot/52145745#52145745
I used :
`VaultResponse response = vaultTemplate.read("/secret/data/github");`
To make it work.
Could you please update the spring guide and provide an explanation for that ? 

Thank

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. Providing Vault versions and some stack trace are a bare minimum.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
